image: touchlay/node-flow

before_script:
  - npm install

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

stages:
  - test
  - deploy

lint:
  stage: test
  script:
    - npm run lint
flow:
  stage: test
  script:
    - npm run flow
test:
  stage: test
  script:
    - npm run coverage

pages:
  stage: deploy
  script:
    - npm run build
  artifacts:
    paths:
    - public
  only:
    - master